2022-01-23 20:12:50,570 INFO     Started server process [19596]
2022-01-23 20:12:50,570 INFO     Waiting for application startup.
2022-01-23 20:12:50,575 INFO     Application startup complete.
2022-01-23 20:12:59,808 INFO     Opened weight page
2022-01-23 20:12:59,913 INFO     Opened height page
2022-01-23 20:12:59,950 INFO     Opened head circumference page
2022-01-23 20:12:59,990 INFO     Opened feeding page
2022-01-23 20:13:01,192 INFO     Opened feeding page
2022-01-23 20:14:19,305 INFO     Started server process [13860]
2022-01-23 20:14:19,305 INFO     Waiting for application startup.
2022-01-23 20:14:19,308 INFO     Application startup complete.
2022-01-23 20:16:02,533 INFO     Started server process [26472]
2022-01-23 20:16:02,541 INFO     Waiting for application startup.
2022-01-23 20:16:02,541 INFO     Application startup complete.
2022-01-23 20:17:08,972 INFO     Opened weight page
2022-01-23 20:17:09,032 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 234, in app
    response_data = await serialize_response(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 137, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 3 validation errors for WeightItem
response -> date
  invalid type; expected date, string, bytes, int or float (type=type_error)
response -> week
  value is not a valid float (type=type_error.float)
response -> weight
  value is not a valid float (type=type_error.float)
2022-01-23 20:18:39,500 INFO     Started server process [28188]
2022-01-23 20:18:39,500 INFO     Waiting for application startup.
2022-01-23 20:18:39,505 INFO     Application startup complete.
2022-01-23 20:18:44,056 INFO     Opened weight page
2022-01-23 20:18:44,110 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 234, in app
    response_data = await serialize_response(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 137, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 3 validation errors for WeightItem
response -> date
  invalid type; expected date, string, bytes, int or float (type=type_error)
response -> week
  value is not a valid float (type=type_error.float)
response -> weight
  value is not a valid float (type=type_error.float)
2022-01-23 20:19:46,189 INFO     Started server process [5956]
2022-01-23 20:19:46,189 INFO     Waiting for application startup.
2022-01-23 20:19:46,197 INFO     Application startup complete.
2022-01-23 20:19:51,333 INFO     Opened weight page
2022-01-23 20:19:51,400 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 234, in app
    response_data = await serialize_response(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 137, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 3 validation errors for WeightItem
response -> date
  invalid type; expected date, string, bytes, int or float (type=type_error)
response -> week
  value is not a valid float (type=type_error.float)
response -> weight
  value is not a valid float (type=type_error.float)
2022-01-23 20:20:24,257 INFO     Started server process [27584]
2022-01-23 20:20:24,257 INFO     Waiting for application startup.
2022-01-23 20:20:24,262 INFO     Application startup complete.
2022-01-23 20:20:27,434 INFO     Opened weight page
2022-01-23 20:20:27,498 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 234, in app
    response_data = await serialize_response(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 137, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 3 validation errors for WeightItem
response -> date
  invalid type; expected date, string, bytes, int or float (type=type_error)
response -> week
  value is not a valid float (type=type_error.float)
response -> weight
  value is not a valid float (type=type_error.float)
2022-01-23 20:20:44,242 INFO     Started server process [22904]
2022-01-23 20:20:44,248 INFO     Waiting for application startup.
2022-01-23 20:20:44,248 INFO     Application startup complete.
2022-01-23 20:21:07,253 INFO     Started server process [27004]
2022-01-23 20:21:07,253 INFO     Waiting for application startup.
2022-01-23 20:21:07,261 INFO     Application startup complete.
2022-01-23 20:21:10,320 INFO     Started server process [15016]
2022-01-23 20:21:10,320 INFO     Waiting for application startup.
2022-01-23 20:21:10,334 INFO     Application startup complete.
2022-01-23 20:21:15,555 INFO     Opened weight page
2022-01-23 20:21:15,621 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 234, in app
    response_data = await serialize_response(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 137, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 3 validation errors for WeightItem
response -> date
  invalid type; expected date, string, bytes, int or float (type=type_error)
response -> week
  value is not a valid float (type=type_error.float)
response -> weight
  value is not a valid float (type=type_error.float)
2022-01-23 20:21:51,556 INFO     Started server process [25604]
2022-01-23 20:21:51,571 INFO     Waiting for application startup.
2022-01-23 20:21:51,572 INFO     Application startup complete.
2022-01-23 20:21:54,626 INFO     Opened weight page
2022-01-23 20:21:54,682 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File ".\app\main.py", line 58, in weight_data_page
    print(result.dtypes)
AttributeError: 'function' object has no attribute 'dtypes'
2022-01-23 20:21:56,532 INFO     Opened weight page
2022-01-23 20:21:56,563 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File ".\app\main.py", line 58, in weight_data_page
    print(result.dtypes)
AttributeError: 'function' object has no attribute 'dtypes'
2022-01-23 20:22:09,028 INFO     Started server process [29508]
2022-01-23 20:22:09,029 INFO     Waiting for application startup.
2022-01-23 20:22:09,030 INFO     Application startup complete.
2022-01-23 20:22:15,285 INFO     Opened weight page
2022-01-23 20:22:15,373 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 234, in app
    response_data = await serialize_response(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 137, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for WeightItem
response
  value is not a valid dict (type=type_error.dict)
2022-01-23 20:26:05,730 INFO     Started server process [24884]
2022-01-23 20:26:05,731 INFO     Waiting for application startup.
2022-01-23 20:26:05,732 INFO     Application startup complete.
2022-01-23 20:26:13,617 INFO     Opened weight page
2022-01-23 20:26:13,689 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 234, in app
    response_data = await serialize_response(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 137, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for WeightItem
response
  value is not a valid dict (type=type_error.dict)
2022-01-23 20:26:31,378 INFO     Started server process [7992]
2022-01-23 20:26:31,378 INFO     Waiting for application startup.
2022-01-23 20:26:31,383 INFO     Application startup complete.
2022-01-23 20:26:34,584 INFO     Opened weight page
2022-01-23 20:26:34,649 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 234, in app
    response_data = await serialize_response(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 137, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 3 validation errors for WeightItem
response -> date
  value is not a valid list (type=type_error.list)
response -> week
  value is not a valid list (type=type_error.list)
response -> weight
  value is not a valid list (type=type_error.list)
2022-01-23 20:27:23,420 INFO     Started server process [25900]
2022-01-23 20:27:23,420 INFO     Waiting for application startup.
2022-01-23 20:27:23,429 INFO     Application startup complete.
2022-01-23 20:27:31,324 INFO     Started server process [14920]
2022-01-23 20:27:31,324 INFO     Waiting for application startup.
2022-01-23 20:27:31,329 INFO     Application startup complete.
2022-01-23 20:27:40,076 INFO     Opened weight page
2022-01-23 20:38:13,177 INFO     Opened weight page
2022-01-23 20:38:21,490 INFO     Opened weight page
2022-01-23 20:38:21,544 INFO     Opened height page
2022-01-23 20:38:21,580 INFO     Opened head circumference page
2022-01-23 20:38:21,618 INFO     Opened feeding page
2022-01-23 20:38:22,777 INFO     Opened feeding page
2022-01-23 21:00:09,466 INFO     Shutting down
2022-01-24 12:40:40,763 INFO     Started server process [30044]
2022-01-24 12:40:40,763 INFO     Waiting for application startup.
2022-01-24 12:40:40,763 INFO     Application startup complete.
2022-01-24 12:41:05,659 INFO     Opened weight page
2022-01-24 12:41:32,021 INFO     Started server process [19312]
2022-01-24 12:41:32,022 INFO     Waiting for application startup.
2022-01-24 12:41:32,022 INFO     Application startup complete.
2022-01-24 12:41:39,517 INFO     Started server process [3180]
2022-01-24 12:41:39,518 INFO     Waiting for application startup.
2022-01-24 12:41:39,519 INFO     Application startup complete.
2022-01-24 12:41:46,431 INFO     Opened weight page
2022-01-24 12:48:10,675 INFO     Started server process [8440]
2022-01-24 12:48:10,676 INFO     Waiting for application startup.
2022-01-24 12:48:10,677 INFO     Application startup complete.
2022-01-24 12:48:47,388 INFO     Started server process [28824]
2022-01-24 12:48:47,388 INFO     Waiting for application startup.
2022-01-24 12:48:47,388 INFO     Application startup complete.
2022-01-24 12:49:12,252 INFO     Started server process [23492]
2022-01-24 12:49:12,253 INFO     Waiting for application startup.
2022-01-24 12:49:12,254 INFO     Application startup complete.
2022-01-24 12:50:12,099 INFO     Started server process [1948]
2022-01-24 12:50:12,100 INFO     Waiting for application startup.
2022-01-24 12:50:12,101 INFO     Application startup complete.
2022-01-24 12:54:06,693 INFO     Started server process [19060]
2022-01-24 12:54:06,694 INFO     Waiting for application startup.
2022-01-24 12:54:06,694 INFO     Application startup complete.
2022-01-24 12:54:36,763 INFO     Started server process [17476]
2022-01-24 12:54:36,763 INFO     Waiting for application startup.
2022-01-24 12:54:36,763 INFO     Application startup complete.
2022-01-24 13:08:32,201 INFO     Started server process [10016]
2022-01-24 13:08:32,202 INFO     Waiting for application startup.
2022-01-24 13:08:32,204 INFO     Application startup complete.
2022-01-24 13:46:48,663 INFO     Started server process [30200]
2022-01-24 13:46:48,679 INFO     Waiting for application startup.
2022-01-24 13:46:48,680 INFO     Application startup complete.
2022-01-24 13:47:09,171 INFO     Started server process [26576]
2022-01-24 13:47:09,172 INFO     Waiting for application startup.
2022-01-24 13:47:09,174 INFO     Application startup complete.
2022-01-24 13:48:21,864 INFO     Started server process [4028]
2022-01-24 13:48:21,864 INFO     Waiting for application startup.
2022-01-24 13:48:21,864 INFO     Application startup complete.
2022-01-24 13:48:39,217 INFO     Started server process [14008]
2022-01-24 13:48:39,217 INFO     Waiting for application startup.
2022-01-24 13:48:39,217 INFO     Application startup complete.
2022-01-24 13:49:12,173 INFO     Opened weight page
2022-01-24 13:52:21,668 INFO     Opened weight page
2022-01-24 14:17:56,805 INFO     Started server process [28796]
2022-01-24 14:17:56,805 INFO     Waiting for application startup.
2022-01-24 14:17:56,805 INFO     Application startup complete.
2022-01-24 14:18:35,178 INFO     Started server process [28016]
2022-01-24 14:18:35,178 INFO     Waiting for application startup.
2022-01-24 14:18:35,183 INFO     Application startup complete.
2022-01-24 14:19:00,841 INFO     Started server process [13520]
2022-01-24 14:19:00,842 INFO     Waiting for application startup.
2022-01-24 14:19:00,843 INFO     Application startup complete.
2022-01-24 14:20:55,034 INFO     Started server process [27288]
2022-01-24 14:20:55,035 INFO     Waiting for application startup.
2022-01-24 14:20:55,036 INFO     Application startup complete.
2022-01-24 14:20:58,464 INFO     Opened weight page
2022-01-24 14:21:46,852 INFO     Started server process [29192]
2022-01-24 14:21:46,852 INFO     Waiting for application startup.
2022-01-24 14:21:46,859 INFO     Application startup complete.
2022-01-24 14:22:09,600 INFO     Started server process [30248]
2022-01-24 14:22:09,601 INFO     Waiting for application startup.
2022-01-24 14:22:09,602 INFO     Application startup complete.
2022-01-24 14:22:37,040 INFO     Started server process [30524]
2022-01-24 14:22:37,041 INFO     Waiting for application startup.
2022-01-24 14:22:37,042 INFO     Application startup complete.
2022-01-24 14:22:48,294 INFO     Opened weight page
2022-01-24 14:23:04,207 INFO     Opened head circumference page
2022-01-24 14:23:12,693 INFO     Opened weight page
2022-01-24 14:23:12,713 INFO     Opened height page
2022-01-24 14:23:12,719 INFO     Opened head circumference page
2022-01-24 14:23:12,754 INFO     Opened feeding page
2022-01-24 14:23:14,590 INFO     Opened feeding page
2022-01-24 14:23:46,156 INFO     Started server process [9652]
2022-01-24 14:23:46,156 INFO     Waiting for application startup.
2022-01-24 14:23:46,160 INFO     Application startup complete.
2022-01-24 14:25:38,595 INFO     Started server process [29124]
2022-01-24 14:25:38,596 INFO     Waiting for application startup.
2022-01-24 14:25:38,597 INFO     Application startup complete.
2022-01-24 14:25:51,003 INFO     Started server process [30232]
2022-01-24 14:25:51,004 INFO     Waiting for application startup.
2022-01-24 14:25:51,004 INFO     Application startup complete.
2022-01-24 14:28:12,046 INFO     Started server process [27536]
2022-01-24 14:28:12,046 INFO     Waiting for application startup.
2022-01-24 14:28:12,047 INFO     Application startup complete.
2022-01-24 14:29:19,554 INFO     Started server process [18408]
2022-01-24 14:29:19,554 INFO     Waiting for application startup.
2022-01-24 14:29:19,560 INFO     Application startup complete.
2022-01-24 14:29:32,537 INFO     Started server process [26196]
2022-01-24 14:29:32,538 INFO     Waiting for application startup.
2022-01-24 14:29:32,539 INFO     Application startup complete.
2022-01-24 14:32:24,065 INFO     Started server process [11096]
2022-01-24 14:32:24,065 INFO     Waiting for application startup.
2022-01-24 14:32:24,070 INFO     Application startup complete.
2022-01-24 14:32:31,672 INFO     Started server process [21944]
2022-01-24 14:32:31,672 INFO     Waiting for application startup.
2022-01-24 14:32:31,678 INFO     Application startup complete.
2022-01-24 14:33:01,740 INFO     Started server process [30484]
2022-01-24 14:33:01,741 INFO     Waiting for application startup.
2022-01-24 14:33:01,742 INFO     Application startup complete.
2022-01-24 14:34:49,451 INFO     Started server process [26396]
2022-01-24 14:34:49,451 INFO     Waiting for application startup.
2022-01-24 14:34:49,452 INFO     Application startup complete.
2022-01-24 14:36:32,869 INFO     Started server process [26960]
2022-01-24 14:36:32,869 INFO     Waiting for application startup.
2022-01-24 14:36:32,869 INFO     Application startup complete.
2022-01-24 14:37:06,328 INFO     Started server process [29728]
2022-01-24 14:37:06,329 INFO     Waiting for application startup.
2022-01-24 14:37:06,330 INFO     Application startup complete.
2022-01-24 14:38:38,016 INFO     Started server process [14304]
2022-01-24 14:38:38,017 INFO     Waiting for application startup.
2022-01-24 14:38:38,018 INFO     Application startup complete.
2022-01-24 14:38:45,231 INFO     Started server process [17040]
2022-01-24 14:38:45,231 INFO     Waiting for application startup.
2022-01-24 14:38:45,231 INFO     Application startup complete.
2022-01-24 14:39:27,907 INFO     Started server process [20940]
2022-01-24 14:39:27,908 INFO     Waiting for application startup.
2022-01-24 14:39:27,909 INFO     Application startup complete.
2022-01-24 14:39:41,249 INFO     Started server process [13904]
2022-01-24 14:39:41,250 INFO     Waiting for application startup.
2022-01-24 14:39:41,251 INFO     Application startup complete.
2022-01-24 14:39:56,080 INFO     Opened weight page
2022-01-24 14:39:56,109 INFO     Opened height page
2022-01-24 14:39:56,130 INFO     Opened head circumference page
2022-01-24 14:39:56,151 INFO     Opened feeding page
2022-01-24 14:39:57,165 INFO     Opened feeding page
2022-01-24 15:32:43,091 INFO     Started server process [13720]
2022-01-24 15:32:43,091 INFO     Waiting for application startup.
2022-01-24 15:32:43,092 INFO     Application startup complete.
2022-01-24 15:34:38,031 INFO     Started server process [21736]
2022-01-24 15:34:38,032 INFO     Waiting for application startup.
2022-01-24 15:34:38,033 INFO     Application startup complete.
2022-01-24 15:35:12,189 INFO     Started server process [27128]
2022-01-24 15:35:12,190 INFO     Waiting for application startup.
2022-01-24 15:35:12,191 INFO     Application startup complete.
2022-01-24 15:36:21,510 INFO     Started server process [28860]
2022-01-24 15:36:21,511 INFO     Waiting for application startup.
2022-01-24 15:36:21,512 INFO     Application startup complete.
2022-01-24 15:37:06,250 INFO     Started server process [18136]
2022-01-24 15:37:06,250 INFO     Waiting for application startup.
2022-01-24 15:37:06,259 INFO     Application startup complete.
2022-01-24 15:38:20,083 INFO     Started server process [5212]
2022-01-24 15:38:20,084 INFO     Waiting for application startup.
2022-01-24 15:38:20,084 INFO     Application startup complete.
2022-01-24 15:38:22,665 INFO     Started server process [30644]
2022-01-24 15:38:22,665 INFO     Waiting for application startup.
2022-01-24 15:38:22,678 INFO     Application startup complete.
2022-01-24 15:39:07,076 INFO     Opened head circumference page
2022-01-24 15:55:03,318 INFO     Started server process [30540]
2022-01-24 15:55:03,319 INFO     Waiting for application startup.
2022-01-24 15:55:03,319 INFO     Application startup complete.
2022-01-24 15:55:24,313 INFO     Opened head circumference page
2022-01-24 16:01:04,214 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File ".\app\main.py", line 107, in update_head
    update_db_head(week, head)
  File ".\app\db_utils.py", line 45, in update_db_head
    cur.execute("INSERT INTO head_table (week, head) VALUES (?,?);", data_tuple)
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 2, and there are 1 supplied.
2022-01-24 16:01:50,792 INFO     Started server process [12588]
2022-01-24 16:01:50,792 INFO     Waiting for application startup.
2022-01-24 16:01:50,792 INFO     Application startup complete.
2022-01-24 16:01:56,498 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File ".\app\main.py", line 107, in update_head
    update_db_head(week, head)
  File ".\app\db_utils.py", line 46, in update_db_head
    cur.execute("INSERT INTO head_table (week, head) VALUES (?,?);", data_tuple)
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 2, and there are 1 supplied.
2022-01-24 16:04:03,088 INFO     Started server process [28384]
2022-01-24 16:04:03,088 INFO     Waiting for application startup.
2022-01-24 16:04:03,094 INFO     Application startup complete.
2022-01-24 16:04:44,271 INFO     Opened head circumference page
2022-01-24 16:05:06,216 INFO     Opened weight page
2022-01-24 16:05:06,238 INFO     Opened height page
2022-01-24 16:05:06,262 INFO     Opened head circumference page
2022-01-24 16:05:06,283 INFO     Opened feeding page
2022-01-24 16:05:07,305 INFO     Opened feeding page
2022-01-24 16:06:36,311 INFO     Started server process [27564]
2022-01-24 16:06:36,312 INFO     Waiting for application startup.
2022-01-24 16:06:36,313 INFO     Application startup complete.
2022-01-24 16:06:50,054 INFO     Opened weight page
2022-01-24 16:06:50,085 INFO     Opened height page
2022-01-24 16:06:50,107 INFO     Opened head circumference page
2022-01-24 16:06:50,128 INFO     Opened feeding page
2022-01-24 16:06:51,116 INFO     Opened feeding page
2022-01-24 16:08:11,455 INFO     Opened weight page
2022-01-24 16:08:11,476 INFO     Opened height page
2022-01-24 16:08:11,514 INFO     Opened head circumference page
2022-01-24 16:08:11,535 INFO     Opened feeding page
2022-01-24 16:08:12,510 INFO     Opened feeding page
2022-01-25 08:42:41,624 INFO     Opened weight page
2022-01-25 08:42:41,673 INFO     Opened height page
2022-01-25 08:42:41,679 INFO     Opened head circumference page
2022-01-25 08:42:41,710 INFO     Opened feeding page
2022-01-25 08:42:42,846 INFO     Opened feeding page
2022-01-25 10:29:36,172 INFO     Opened head circumference page
2022-01-25 10:30:18,271 INFO     Opened head circumference page
2022-01-25 10:31:41,737 INFO     Opened head circumference page
2022-01-25 10:35:24,399 INFO     Opened head circumference page
2022-01-25 10:37:35,523 INFO     Started server process [20956]
2022-01-25 10:37:35,523 INFO     Waiting for application startup.
2022-01-25 10:37:35,527 INFO     Application startup complete.
2022-01-25 11:03:44,107 INFO     Started server process [31420]
2022-01-25 11:03:44,108 INFO     Waiting for application startup.
2022-01-25 11:03:44,109 INFO     Application startup complete.
2022-01-25 11:04:42,959 INFO     Opened head circumference page
2022-01-25 11:05:06,110 INFO     Started server process [31188]
2022-01-25 11:05:06,111 INFO     Waiting for application startup.
2022-01-25 11:05:06,112 INFO     Application startup complete.
2022-01-25 11:05:37,997 INFO     Started server process [27952]
2022-01-25 11:05:37,997 INFO     Waiting for application startup.
2022-01-25 11:05:38,001 INFO     Application startup complete.
2022-01-25 11:06:18,009 INFO     Started server process [8100]
2022-01-25 11:06:18,010 INFO     Waiting for application startup.
2022-01-25 11:06:18,011 INFO     Application startup complete.
2022-01-25 11:08:14,037 INFO     Opened head circumference page
2022-01-25 11:14:39,686 INFO     Opened head circumference page
2022-01-25 11:15:08,794 INFO     Started server process [30992]
2022-01-25 11:15:08,795 INFO     Waiting for application startup.
2022-01-25 11:15:08,796 INFO     Application startup complete.
2022-01-25 11:15:25,985 INFO     Started server process [3432]
2022-01-25 11:15:25,986 INFO     Waiting for application startup.
2022-01-25 11:15:25,987 INFO     Application startup complete.
2022-01-25 11:15:30,222 INFO     Opened weight page
2022-01-25 11:15:30,259 INFO     Opened height page
2022-01-25 11:15:30,284 INFO     Opened head circumference page
2022-01-25 11:15:30,309 INFO     Opened feeding page
2022-01-25 11:15:31,321 INFO     Opened feeding page
2022-01-25 12:53:14,358 INFO     Started server process [28576]
2022-01-25 12:53:14,359 INFO     Waiting for application startup.
2022-01-25 12:53:14,360 INFO     Application startup complete.
2022-01-25 12:55:19,621 INFO     Started server process [13976]
2022-01-25 12:55:19,621 INFO     Waiting for application startup.
2022-01-25 12:55:19,627 INFO     Application startup complete.
2022-01-25 12:57:02,013 INFO     Started server process [27576]
2022-01-25 12:57:02,013 INFO     Waiting for application startup.
2022-01-25 12:57:02,024 INFO     Application startup complete.
2022-01-25 12:57:23,051 INFO     Started server process [31028]
2022-01-25 12:57:23,051 INFO     Waiting for application startup.
2022-01-25 12:57:23,053 INFO     Application startup complete.
2022-01-25 12:57:26,030 INFO     Started server process [30604]
2022-01-25 12:57:26,030 INFO     Waiting for application startup.
2022-01-25 12:57:26,042 INFO     Application startup complete.
2022-01-25 13:03:58,135 INFO     Opened weight page
2022-01-25 13:03:58,162 INFO     Opened height page
2022-01-25 13:03:58,188 INFO     Opened head circumference page
2022-01-25 13:03:58,209 INFO     Opened feeding page
2022-01-25 13:03:59,248 INFO     Opened feeding page
2022-01-25 13:05:31,305 INFO     Opened weight page
2022-01-25 13:05:31,329 INFO     Opened height page
2022-01-25 13:05:31,352 INFO     Opened head circumference page
2022-01-25 13:05:31,374 INFO     Opened feeding page
2022-01-25 13:05:32,384 INFO     Opened feeding page
2022-01-25 13:08:11,398 INFO     Opened weight page
2022-01-25 13:08:11,427 INFO     Opened height page
2022-01-25 13:08:11,450 INFO     Opened head circumference page
2022-01-25 13:08:11,471 INFO     Opened feeding page
2022-01-25 13:08:12,458 INFO     Opened feeding page
2022-01-25 13:08:32,915 INFO     Opened weight page
2022-01-25 13:08:32,943 INFO     Opened height page
2022-01-25 13:08:32,965 INFO     Opened head circumference page
2022-01-25 13:08:32,985 INFO     Opened feeding page
2022-01-25 13:08:34,011 INFO     Opened feeding page
2022-01-25 13:15:01,798 INFO     Opened head circumference page
2022-01-25 13:15:39,932 INFO     Opened head circumference page
2022-01-25 13:17:42,203 INFO     Opened weight page
2022-01-25 13:17:42,231 INFO     Opened height page
2022-01-25 13:17:42,252 INFO     Opened head circumference page
2022-01-25 13:17:42,273 INFO     Opened feeding page
2022-01-25 13:17:43,343 INFO     Opened feeding page
2022-01-25 13:38:55,957 INFO     Opened weight page
2022-01-25 13:38:55,994 INFO     Opened height page
2022-01-25 13:38:56,014 INFO     Opened head circumference page
2022-01-25 13:38:56,032 INFO     Opened feeding page
2022-01-25 13:38:57,040 INFO     Opened feeding page
2022-01-25 14:47:41,403 INFO     Opened weight page
2022-01-25 14:47:41,430 INFO     Opened height page
2022-01-25 14:47:41,451 INFO     Opened head circumference page
2022-01-25 14:47:41,471 INFO     Opened feeding page
2022-01-25 14:47:42,506 INFO     Opened feeding page
2022-01-25 14:50:06,365 INFO     Opened weight page
2022-01-25 14:50:06,392 INFO     Opened height page
2022-01-25 14:50:06,407 INFO     Opened head circumference page
2022-01-25 14:50:06,430 INFO     Opened feeding page
2022-01-25 14:50:07,455 INFO     Opened feeding page
2022-01-25 14:50:47,486 INFO     Opened weight page
2022-01-25 14:50:47,504 INFO     Opened height page
2022-01-25 14:50:47,533 INFO     Opened head circumference page
2022-01-25 14:50:47,557 INFO     Opened feeding page
2022-01-25 14:50:48,649 INFO     Opened feeding page
2022-01-25 15:27:12,071 INFO     Opened weight page
2022-01-25 15:27:12,097 INFO     Opened height page
2022-01-25 15:27:12,116 INFO     Opened head circumference page
2022-01-25 15:27:12,135 INFO     Opened feeding page
2022-01-25 15:27:13,188 INFO     Opened feeding page
2022-01-25 15:27:57,364 INFO     Opened weight page
2022-01-25 15:27:57,386 INFO     Opened height page
2022-01-25 15:27:57,397 INFO     Opened head circumference page
2022-01-25 15:27:57,425 INFO     Opened feeding page
2022-01-25 15:27:58,395 INFO     Opened feeding page
2022-01-25 15:28:07,010 INFO     Opened head circumference page
2022-01-25 16:03:53,035 INFO     Started server process [9524]
2022-01-25 16:03:53,036 INFO     Waiting for application startup.
2022-01-25 16:03:53,037 INFO     Application startup complete.
2022-01-25 16:05:20,102 INFO     Started server process [30724]
2022-01-25 16:05:20,102 INFO     Waiting for application startup.
2022-01-25 16:05:20,110 INFO     Application startup complete.
2022-01-25 16:12:50,426 INFO     Started server process [31096]
2022-01-25 16:12:50,426 INFO     Waiting for application startup.
2022-01-25 16:12:50,433 INFO     Application startup complete.
2022-01-25 16:12:50,435 INFO     Opened weight page
2022-01-25 16:13:57,279 INFO     Opened feeding page
2022-01-25 16:15:56,132 INFO     Started server process [25016]
2022-01-25 16:15:56,132 INFO     Waiting for application startup.
2022-01-25 16:15:56,148 INFO     Application startup complete.
2022-01-25 16:16:02,081 INFO     Opened feeding page
2022-01-25 16:20:55,208 INFO     Started server process [2164]
2022-01-25 16:20:55,209 INFO     Waiting for application startup.
2022-01-25 16:20:55,210 INFO     Application startup complete.
2022-01-25 16:21:04,187 INFO     Started server process [17360]
2022-01-25 16:21:04,188 INFO     Waiting for application startup.
2022-01-25 16:21:04,189 INFO     Application startup complete.
2022-01-25 16:23:24,847 INFO     Started server process [28828]
2022-01-25 16:23:24,848 INFO     Waiting for application startup.
2022-01-25 16:23:24,849 INFO     Application startup complete.
2022-01-25 16:23:30,357 INFO     Started server process [28332]
2022-01-25 16:23:30,358 INFO     Waiting for application startup.
2022-01-25 16:23:30,358 INFO     Application startup complete.
2022-01-25 16:23:42,708 INFO     Started server process [26904]
2022-01-25 16:23:42,708 INFO     Waiting for application startup.
2022-01-25 16:23:42,708 INFO     Application startup complete.
2022-01-25 16:27:02,177 INFO     Opened weight page
2022-01-25 16:27:41,634 INFO     Opened weight page
2022-01-25 16:33:52,631 INFO     Started server process [6728]
2022-01-25 16:33:52,632 INFO     Waiting for application startup.
2022-01-25 16:33:52,633 INFO     Application startup complete.
2022-01-25 16:34:00,711 INFO     Started server process [13532]
2022-01-25 16:34:00,711 INFO     Waiting for application startup.
2022-01-25 16:34:00,711 INFO     Application startup complete.
2022-01-25 16:40:40,970 INFO     Opened weight page
2022-01-25 16:40:40,997 INFO     Opened height page
2022-01-25 16:40:41,024 INFO     Opened head circumference page
2022-01-25 16:40:41,044 INFO     Opened feeding page
2022-01-25 16:40:42,119 INFO     Opened feeding page
2022-01-25 16:41:23,825 INFO     Opened weight page
2022-01-25 16:41:40,482 INFO     Opened weight page
2022-01-25 16:41:44,080 INFO     Opened weight page
2022-01-25 16:41:44,103 INFO     Opened height page
2022-01-25 16:41:44,125 INFO     Opened head circumference page
2022-01-25 16:41:44,150 INFO     Opened feeding page
2022-01-25 16:41:45,188 INFO     Opened feeding page
2022-01-25 17:10:45,372 INFO     Started server process [6404]
2022-01-25 17:10:45,372 INFO     Waiting for application startup.
2022-01-25 17:10:45,387 INFO     Application startup complete.
2022-01-25 17:11:24,715 INFO     Started server process [18352]
2022-01-25 17:11:24,715 INFO     Waiting for application startup.
2022-01-25 17:11:24,716 INFO     Application startup complete.
2022-01-25 17:11:41,492 INFO     Started server process [5012]
2022-01-25 17:11:41,494 INFO     Waiting for application startup.
2022-01-25 17:11:41,494 INFO     Application startup complete.
2022-01-25 17:17:14,719 INFO     Started server process [14660]
2022-01-25 17:17:14,720 INFO     Waiting for application startup.
2022-01-25 17:17:14,720 INFO     Application startup complete.
2022-01-25 17:18:36,173 INFO     Started server process [26628]
2022-01-25 17:18:36,183 INFO     Waiting for application startup.
2022-01-25 17:18:36,184 INFO     Application startup complete.
2022-01-25 17:19:54,808 INFO     Started server process [20800]
2022-01-25 17:19:54,808 INFO     Waiting for application startup.
2022-01-25 17:19:54,813 INFO     Application startup complete.
2022-01-25 17:20:04,684 INFO     Started server process [24120]
2022-01-25 17:20:04,684 INFO     Waiting for application startup.
2022-01-25 17:20:04,684 INFO     Application startup complete.
2022-01-25 17:20:16,629 INFO     Started server process [26196]
2022-01-25 17:20:16,630 INFO     Waiting for application startup.
2022-01-25 17:20:16,630 INFO     Application startup complete.
2022-01-25 17:23:21,796 INFO     Started server process [6780]
2022-01-25 17:23:21,796 INFO     Waiting for application startup.
2022-01-25 17:23:21,796 INFO     Application startup complete.
2022-01-25 17:23:53,030 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File ".\app\main.py", line 120, in update_wnh
    update_db_feeding(date, time, bm_vol, formula_vol)
  File ".\app\db_utils.py", line 64, in update_db_feeding
    cur.execute("INSERT INTO weight_table (date, time, bm_vol, formula_vol) VALUES (?,?,?,?);", data_tuple)
sqlite3.OperationalError: table weight_table has no column named time
2022-01-25 17:24:09,230 INFO     Started server process [21736]
2022-01-25 17:24:09,230 INFO     Waiting for application startup.
2022-01-25 17:24:09,230 INFO     Application startup complete.
2022-01-25 17:24:51,360 INFO     Opened feeding page
2022-01-25 17:24:51,360 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File ".\app\main.py", line 94, in feeding
    result = get_db_data("feeding")
  File ".\app\db_utils.py", line 28, in get_db_data
    df['total_vol'] = df.bm_vol.astype(int) + df.formula_vol.astype(int)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\generic.py", line 5815, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 418, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\internals\blocks.py", line 591, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 1309, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 1257, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 1174, in astype_nansafe
    return lib.astype_intsafe(arr, dtype)
  File "pandas\_libs\lib.pyx", line 679, in pandas._libs.lib.astype_intsafe
ValueError: invalid literal for int() with base 10: '120.0'
2022-01-25 17:25:01,422 INFO     Opened weight page
2022-01-25 17:25:06,629 INFO     Opened height page
2022-01-25 17:25:25,935 INFO     Opened weight page
2022-01-25 17:27:50,694 INFO     Started server process [31112]
2022-01-25 17:27:50,695 INFO     Waiting for application startup.
2022-01-25 17:27:50,696 INFO     Application startup complete.
2022-01-25 17:28:46,030 INFO     Opened weight page
2022-01-25 17:28:54,048 INFO     Opened feeding page
2022-01-25 17:28:54,048 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File ".\app\main.py", line 94, in feeding
    result = get_db_data("feeding")
  File ".\app\db_utils.py", line 28, in get_db_data
    df['total_vol'] = df.bm_vol.astype(int) + df.formula_vol.astype(int)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\generic.py", line 5815, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 418, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\internals\blocks.py", line 591, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 1309, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 1257, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 1174, in astype_nansafe
    return lib.astype_intsafe(arr, dtype)
  File "pandas\_libs\lib.pyx", line 679, in pandas._libs.lib.astype_intsafe
ValueError: invalid literal for int() with base 10: '120.0'
2022-01-25 19:53:35,004 INFO     Opened weight page
2022-01-25 19:54:56,713 INFO     Opened feeding page
2022-01-25 19:54:56,716 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File ".\app\main.py", line 94, in feeding
    result = get_db_data("feeding")
  File ".\app\db_utils.py", line 28, in get_db_data
    df['total_vol'] = df.bm_vol.astype(int) + df.formula_vol.astype(int)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\generic.py", line 5815, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 418, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\internals\blocks.py", line 591, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 1309, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 1257, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 1174, in astype_nansafe
    return lib.astype_intsafe(arr, dtype)
  File "pandas\_libs\lib.pyx", line 679, in pandas._libs.lib.astype_intsafe
ValueError: invalid literal for int() with base 10: '120.0'
2022-01-25 19:58:22,749 INFO     Opened weight page
2022-01-25 19:58:22,774 INFO     Opened height page
2022-01-25 19:58:22,795 INFO     Opened head circumference page
2022-01-25 19:58:22,817 INFO     Opened feeding page
2022-01-25 19:58:22,822 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File ".\app\main.py", line 94, in feeding
    result = get_db_data("feeding")
  File ".\app\db_utils.py", line 28, in get_db_data
    df['total_vol'] = df.bm_vol.astype(int) + df.formula_vol.astype(int)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\generic.py", line 5815, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 418, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\internals\blocks.py", line 591, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 1309, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 1257, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 1174, in astype_nansafe
    return lib.astype_intsafe(arr, dtype)
  File "pandas\_libs\lib.pyx", line 679, in pandas._libs.lib.astype_intsafe
ValueError: invalid literal for int() with base 10: '120.0'
2022-01-25 19:58:59,807 INFO     Opened head circumference page
2022-01-25 20:01:12,429 INFO     Opened head circumference page
2022-01-25 20:02:42,848 INFO     Opened weight page
2022-01-25 20:02:42,871 INFO     Opened height page
2022-01-25 20:02:42,894 INFO     Opened head circumference page
2022-01-25 20:02:42,921 INFO     Opened feeding page
2022-01-25 20:02:43,921 INFO     Opened feeding page
2022-01-25 20:05:44,788 INFO     Opened head circumference page
2022-01-25 20:05:51,438 INFO     Opened weight page
2022-01-25 20:06:00,777 INFO     Opened feeding page
2022-01-25 20:06:11,545 INFO     Opened weight page
2022-01-25 20:06:11,566 INFO     Opened height page
2022-01-25 20:06:11,585 INFO     Opened head circumference page
2022-01-25 20:06:11,605 INFO     Opened feeding page
2022-01-25 20:06:12,742 INFO     Opened feeding page
2022-01-25 21:16:59,330 INFO     Opened weight page
2022-01-25 21:16:59,359 INFO     Opened height page
2022-01-25 21:16:59,379 INFO     Opened head circumference page
2022-01-25 21:16:59,399 INFO     Opened feeding page
2022-01-25 21:17:00,407 INFO     Opened feeding page
2022-01-25 23:02:37,449 INFO     Opened weight page
2022-01-25 23:02:37,491 INFO     Opened height page
2022-01-25 23:02:37,512 INFO     Opened head circumference page
2022-01-25 23:02:37,535 INFO     Opened feeding page
2022-01-25 23:02:38,680 INFO     Opened feeding page
2022-01-25 23:02:53,716 INFO     Opened weight page
2022-01-25 23:02:53,759 INFO     Opened height page
2022-01-25 23:02:53,785 INFO     Opened head circumference page
2022-01-25 23:02:53,810 INFO     Opened feeding page
2022-01-25 23:02:54,810 INFO     Opened feeding page
2022-01-25 23:05:12,252 INFO     Started server process [19104]
2022-01-25 23:05:12,253 INFO     Waiting for application startup.
2022-01-25 23:05:12,254 INFO     Application startup complete.
2022-01-25 23:05:21,944 INFO     Started server process [29880]
2022-01-25 23:05:21,944 INFO     Waiting for application startup.
2022-01-25 23:05:21,947 INFO     Application startup complete.
2022-01-25 23:07:37,321 INFO     Opened weight page
2022-01-25 23:07:37,353 INFO     Opened height page
2022-01-25 23:07:37,373 INFO     Opened head circumference page
2022-01-25 23:07:37,394 INFO     Opened feeding page
2022-01-25 23:07:38,358 INFO     Opened feeding page
2022-01-25 23:07:46,393 INFO     Opened weight page
2022-01-25 23:07:46,428 INFO     Opened height page
2022-01-25 23:07:46,455 INFO     Opened head circumference page
2022-01-25 23:07:46,476 INFO     Opened feeding page
2022-01-25 23:07:47,473 INFO     Opened feeding page
2022-01-25 23:09:25,429 INFO     Opened weight page
2022-01-25 23:09:25,456 INFO     Opened height page
2022-01-25 23:09:25,479 INFO     Opened head circumference page
2022-01-25 23:09:25,500 INFO     Opened feeding page
2022-01-25 23:09:26,465 INFO     Opened feeding page
2022-01-25 23:09:41,102 INFO     Opened weight page
2022-01-25 23:09:41,125 INFO     Opened height page
2022-01-25 23:09:41,145 INFO     Opened head circumference page
2022-01-25 23:09:41,165 INFO     Opened feeding page
2022-01-25 23:09:42,204 INFO     Opened feeding page
2022-01-25 23:22:20,466 INFO     Opened weight page
2022-01-25 23:22:20,492 INFO     Opened height page
2022-01-25 23:22:20,509 INFO     Opened head circumference page
2022-01-25 23:22:20,533 INFO     Opened feeding page
2022-01-25 23:22:21,558 INFO     Opened feeding page
2022-01-25 23:23:34,122 INFO     Opened weight page
2022-01-25 23:23:34,146 INFO     Opened height page
2022-01-25 23:23:34,157 INFO     Opened head circumference page
2022-01-25 23:23:34,187 INFO     Opened feeding page
2022-01-25 23:23:35,206 INFO     Opened feeding page
2022-01-25 23:26:22,206 INFO     Opened weight page
2022-01-25 23:26:22,229 INFO     Opened height page
2022-01-25 23:26:22,259 INFO     Opened head circumference page
2022-01-25 23:26:22,279 INFO     Opened feeding page
2022-01-25 23:26:23,397 INFO     Opened feeding page
2022-01-25 23:26:37,614 INFO     Opened weight page
2022-01-25 23:26:37,638 INFO     Opened height page
2022-01-25 23:26:37,658 INFO     Opened head circumference page
2022-01-25 23:26:37,679 INFO     Opened feeding page
2022-01-25 23:26:38,703 INFO     Opened feeding page
2022-01-25 23:28:12,417 INFO     Opened weight page
2022-01-25 23:28:12,445 INFO     Opened height page
2022-01-25 23:28:12,467 INFO     Opened head circumference page
2022-01-25 23:28:12,489 INFO     Opened feeding page
2022-01-25 23:28:13,558 INFO     Opened feeding page
2022-01-25 23:31:30,564 INFO     Opened weight page
2022-01-25 23:31:30,599 INFO     Opened height page
2022-01-25 23:31:30,619 INFO     Opened head circumference page
2022-01-25 23:31:30,640 INFO     Opened feeding page
2022-01-25 23:31:31,612 INFO     Opened feeding page
2022-01-25 23:36:27,526 INFO     Opened weight page
2022-01-25 23:36:27,546 INFO     Opened height page
2022-01-25 23:36:27,594 INFO     Opened head circumference page
2022-01-25 23:36:27,615 INFO     Opened feeding page
2022-01-25 23:36:28,709 INFO     Opened feeding page
2022-01-25 23:36:43,044 INFO     Opened weight page
2022-01-25 23:36:43,074 INFO     Opened height page
2022-01-25 23:36:43,093 INFO     Opened head circumference page
2022-01-25 23:36:43,113 INFO     Opened feeding page
2022-01-25 23:36:44,025 INFO     Opened feeding page
2022-01-26 10:23:46,908 INFO     Opened weight page
2022-01-26 10:23:46,934 INFO     Opened height page
2022-01-26 10:23:46,940 INFO     Opened head circumference page
2022-01-26 10:23:46,979 INFO     Opened feeding page
2022-01-26 10:23:47,997 INFO     Opened feeding page
2022-01-26 10:26:51,854 INFO     Opened weight page
2022-01-26 10:26:51,887 INFO     Opened height page
2022-01-26 10:26:51,907 INFO     Opened head circumference page
2022-01-26 10:26:51,928 INFO     Opened feeding page
2022-01-26 10:26:52,934 INFO     Opened feeding page
2022-01-26 10:40:43,849 INFO     Opened weight page
2022-01-26 10:40:43,872 INFO     Opened height page
2022-01-26 10:40:43,897 INFO     Opened head circumference page
2022-01-26 10:40:43,920 INFO     Opened feeding page
2022-01-26 10:40:44,929 INFO     Opened feeding page
2022-01-26 13:58:08,406 INFO     Opened weight page
2022-01-26 13:58:08,448 INFO     Opened height page
2022-01-26 13:58:08,469 INFO     Opened head circumference page
2022-01-26 13:58:08,491 INFO     Opened feeding page
2022-01-26 13:58:09,533 INFO     Opened feeding page
2022-01-26 13:58:31,323 INFO     Opened weight page
2022-01-26 13:58:31,358 INFO     Opened height page
2022-01-26 13:58:31,378 INFO     Opened head circumference page
2022-01-26 13:58:31,397 INFO     Opened feeding page
2022-01-26 13:58:32,324 INFO     Opened feeding page
2022-01-26 15:26:04,996 INFO     Shutting down
2022-01-26 15:26:05,109 INFO     Waiting for application shutdown.
2022-01-26 15:26:05,114 INFO     Application shutdown complete.
2022-01-26 15:26:05,116 INFO     Finished server process [29880]
